language: ruby
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - jruby-9.0.5.0
gemfile:
  - gemfiles/ar50.gemfile
matrix:
  allow_failures:
    - rvm: jruby-9.0.5.0

# trusty (ubuntu 14) which we use in prod and postgresql 9.5 aren't available in container builds:  # https://docs.travis-ci.com/user/database-setup/#PostgreSQL
dist: trusty
sudo: required
addons:
  postgresql: "9.5"
before_script:
  - psql -U postgres -c "create database postgis_adapter_test"
  - sudo apt-get install postgresql-9.5-postgis-2.2 postgresql-9.5-postgis-2.2-scripts
  - psql -U postgres -c "create extension postgis version '2.2.2'"
script: bundle exec rake test
