language: ruby
rvm:
  - 2.3.1
  - 2.2.5
  - jruby-9.0.5.0
gemfile:
  - gemfiles/ar50.gemfile
matrix:
  allow_failures:
    - rvm: jruby-9.0.5.0

# trusty (ubuntu 14) which we use in prod and postgresql 9.5 aren't available in container builds:  # https://docs.travis-ci.com/user/database-setup/#PostgreSQL
dist: trusty
sudo: required
addons:
  postgresql: "9.5"

before_script:
  - psql -U postgres -c "create database postgis_adapter_test"
  - psql -U postgres -d postgis_adapter_test -c "create extension postgis"
script: bundle exec rake test
